In [3]:
import numpy as np
list=[[1,2,3],[5,-6,7]]
data=np.array(list)
data*10

array([[ 10,  20,  30],
       [ 50, -60,  70]])

In [4]:
data+data

array([[  2,   4,   6],
       [ 10, -12,  14]])

In [5]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('int32')

In [9]:
data.ndim

2

In [10]:
np.empty((2,3,4))

array([[[  9.12454591e-312,   9.12433939e-312,   1.69121096e-306,
           1.33511562e-306],
        [  1.89146896e-307,   1.37961302e-306,   1.05699242e-307,
           8.01097889e-307],
        [  1.78020169e-306,   7.56601165e-307,   1.02359984e-306,
           1.42417221e-306]],

       [[  1.42419530e-306,   1.37962456e-306,   1.11260959e-306,
           9.34603679e-307],
        [  1.11260348e-306,   1.33511562e-306,   1.11260348e-306,
           1.33511562e-306],
        [  1.33510679e-306,   8.90098127e-307,   1.29061821e-306,
           8.90104239e-307]]])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
arr=np.array([1,2,3],dtype=np.float64)
arr

array([ 1.,  2.,  3.])

In [14]:
int_arr=arr.astype(np.int32)
int_arr

array([1, 2, 3])

In [15]:
arr*5

array([  5.,  10.,  15.])

In [17]:
arr1=np.arange(10)
arr1[5]

5

In [21]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr3d[1]=55
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[55, 55, 55],
        [55, 55, 55]]])

In [24]:
arr3d[0,1,2]

6

In [25]:
arr3d[1]=-1
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[-1, -1, -1],
        [-1, -1, -1]]])

In [26]:
arr3d[arr3d<1]=999
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[999, 999, 999],
        [999, 999, 999]]])

In [28]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [29]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [35]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [37]:
a=arr[[1,5,7,2]]
a

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [39]:
b=a[:,[0,3,1,2]]
b

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [40]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [42]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [43]:
(arr>20).sum()

11

In [45]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6,23],[-1,7],[8,9]])
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])